version: "3.9"

services:  
  leagueify-webapp:
    # user: 1000:1000
    container_name: leagueify-webapp-dev
    image: leagueify
    build: 
      context: .
      target: development
    environment:
      PUBLIC_SENTRY: false
    command: npm run dev
    # Need to make hose files present in the container
    # Adding the volumes below override the root files
    # volumes:
    #   - ./:/usr/src/app/
    #   - ./services/user/pages/api:/usr/src/app/pages/api/
    #   - ./services/user/public:/usr/src/app/public/user/
    #   - ./services/user/styles:/usr/src/app/styles/user/

  # leagueify-database:
  #   container_name: leagueify-database-dev
  #   ports:
  #     - 27017:27017
