version: "3.9"

services:
  traefik:
    container_name: leagueify-traefik
    image: traefik:v2.10.7
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.api.address=:8000
    ports:
      - 80:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  leagueify:
    container_name: leagueify
    image: ghcr.io/leagueify/server:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.leagueify.entrypoints=api
      - traefik.http.routers.leagueify.rule=PathPrefix(`/`)
      - traefik.http.middlewares.leagueify.ratelimit.average=100
    expose:
      - 8000
    restart: always

