name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    # services:
    #   leagueify-database:
    #     image: mongo:6.0.3
    #     env:
    #       MONGO_INITDB_ROOT_USERNAME: leagueify
    #       MONGO_INITDB_ROOT_PASSWORD: password
    #     ports:
    #       - 27017:27017

    steps:
      - name: Checkout Leagueify Repo
        uses: actions/checkout@v3

      - name: Prepare Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install Leagueify Dependencies
        run: npm ci

      - name: Install Playwright and Run Leagueify Tests
        run: docker-compose run --rm leagueify-webapp npx playwright install && PUBLIC_SENTRY_DSN=${{ secrets.SENTRY_DSN }} PUBLIC_SENTRY_ENV=development DATABASE_URI=mongodb://localhost:27017/leagueify DATABASE_USER=leagueify DATABASE_PASS=password npm run test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: results.xml
          path: test-results

      - name: Tear Down Docker Stack
        if: always()
        run: docker-compose down -v
